### ISSUE TITLE
求提供自定义背景的方法

### ISSUE THREAD

**Issue by Kainichy** [kasuganosoras/cloudflare-worker-blog#10]
如题，想要示例里面一样的自定义背景功能……
大佬可以提供一下方法吗……

**Comment by kasuganosoras** [comment]
改 css 即可，给 body 加 background
```css
body {
    background-image: url(图片地址);
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
}
```
